
-- Create Cost Centers Table
CREATE TABLE IF NOT EXISTS public.cost_centers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text UNIQUE NOT NULL, -- e.g., 'CC-001'
    name text NOT NULL, -- e.g., 'Pabellón A', 'Oficina Nacional'
    description text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.cost_centers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read access for all authenticated users" ON public.cost_centers FOR SELECT USING (auth.role() = 'authenticated');

-- Insert Initial Data (defaults based on conversation)
INSERT INTO public.cost_centers (code, name, description) VALUES
('GRAL', 'General / Sin Asignar', 'Gastos generales no específicos'),
('PAB-A', 'Pabellón A', 'Aulas y laboratorios del Pabellón A'),
('PAB-B', 'Pabellón B', 'Aulas y oficinas del Pabellón B'),
('ADM', 'Administración', 'Oficinas administrativas centrales'),
('LOG', 'Logística y Almacén', 'Área de operaciones logísticas'),
('TEC', 'Tecnología y Sistemas', 'Infraestructura TI'),
('JAR', 'Jardines y Exteriores', 'Mantenimiento de áreas verdes'),
('TES', 'Tesorería y Finanzas', 'Oficinas financieras')
ON CONFLICT (code) DO NOTHING;

-- Add Foreign Key to Orders
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS cost_center_id bigint REFERENCES public.cost_centers(id);

-- Make it clean (optional update existing orders to default if needed, but we'll leave null for legacy)
