
-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL, -- 'Tecnología', 'Mobiliario', etc.
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Read access for authenticated users" ON public.categories;
CREATE POLICY "Read access for authenticated users" ON public.categories FOR SELECT USING (auth.role() = 'authenticated');

-- Insert User Defined Categories
INSERT INTO public.categories (name) VALUES
('Tecnología'),
('Mobiliario'),
('Insumos de limpieza'),
('Útiles de oficina'),
('Salud'),
('Reconocimientos'),
('Donación'),
('Productos de mantenimiento'),
('Otros / General')
ON CONFLICT (name) DO NOTHING;

-- 2. Update Suppliers Table (Each supplier belongs to a primary category)
ALTER TABLE public.suppliers 
ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.categories(id);

-- 3. Update Orders Table (Each order is classified)
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.categories(id);

-- RLS Update for new categories table? Already added above.
