
-- ==============================================================================
-- SENIOR DATA ARCHITECT - SCHEMA REFACTORING PLAN
-- OBJECTIVE: Optimize "Purchase Order" entity for Business Intelligence & Data Integrity
-- ==============================================================================

-- 1. ENUMS (Strict Typing for Data Quality)
-- ==============================================================================
CREATE TYPE public.purchase_type_enum AS ENUM ('CAPEX', 'OPEX', 'REPOSICION', 'URGENCIA');
CREATE TYPE public.currency_enum AS ENUM ('USD', 'PEN', 'EUR');
CREATE TYPE public.payment_condition_enum AS ENUM ('30_DIAS', '60_DIAS', 'CONTADO');
CREATE TYPE public.incoterm_enum AS ENUM ('FOB', 'CIF', 'DDP', 'EXW');
CREATE TYPE public.uom_enum AS ENUM ('UND', 'CAJA', 'KG', 'LT', 'MTR', 'GLN', 'JGO'); 
-- Added MTR, GLN, JGO as common extras, can be trimmed.

-- Aligning Department with User's recent request (Normalized)
CREATE TYPE public.department_enum AS ENUM (
    'LOGISTICA', 
    'MANTENIMIENTO', 
    'CONTABILIDAD', 
    'OFICINA_NACIONAL', 
    'COMUNICACIONES_SISTEMAS'
);

-- 2. MASTER TABLES (Normalization)
-- ==============================================================================

-- 2.1 LOCATIONS (For Delivery Integrity)
CREATE TABLE public.locations (
    id bigint generated by default as identity primary key,
    name text not null, -- e.g. "Almacén Central - Lima"
    address text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2.2 PRODUCTS (SKU Master for Spend Analysis)
CREATE TABLE public.products (
    id bigint generated by default as identity primary key,
    sku text unique not null,
    name text not null,
    category text, -- For Spend Analysis aggregations
    default_uom public.uom_enum default 'UND',
    unit_price_ref numeric(10,4), -- Base reference price
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. UPDATING EXISTING TABLES (Refactoring)
-- ==============================================================================

-- 3.1 ORDERS TABLE
ALTER TABLE public.orders
    -- Header - BI Critical Fields
    ADD COLUMN IF NOT EXISTS required_date date, -- Critical for OTIF KPI
    ADD COLUMN IF NOT EXISTS purchase_type public.purchase_type_enum, -- Critical for CAPEX vs OPEX analysis
    
    -- Vendor / Commercial Terms
    ADD COLUMN IF NOT EXISTS payment_condition public.payment_condition_enum DEFAULT '30_DIAS',
    ADD COLUMN IF NOT EXISTS currency public.currency_enum DEFAULT 'PEN',
    
    -- Logistics
    ADD COLUMN IF NOT EXISTS incoterm public.incoterm_enum DEFAULT 'DDP',
    ADD COLUMN IF NOT EXISTS delivery_location_id bigint REFERENCES public.locations(id);

-- 3.2 DATA CLEANING & MIGRATION (Department)
-- We need to convert existing text text departments to the new Enum if possible, 
-- or leave null if they don't match. 
-- *For this script, we will Add the column first.*
ALTER TABLE public.orders 
    ADD COLUMN IF NOT EXISTS department_enum public.department_enum;

-- 3.3 ORDER ITEMS TABLE
ALTER TABLE public.order_items
    ADD COLUMN IF NOT EXISTS product_id bigint REFERENCES public.products(id),
    ADD COLUMN IF NOT EXISTS cost_center_id bigint; -- Optional FK if you have a Cost Center table

-- 4. RLS POLICIES FOR NEW TABLES
-- ==============================================================================
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Read access for authenticated" ON public.locations FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Read access for authenticated" ON public.products FOR SELECT USING (auth.role() = 'authenticated');

-- 5. REFRESH API SCHEMA (If keeping the strict API config)
-- ==============================================================================
-- If you are using the 'api' schema approach, you would need to update the views here.
-- For now, we assume public access is enabled or you will manually update views.
