version: 1
environment:
  variables:
    DB_HOST: "tu-endpoint-rds.region.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "postgres"
    DB_USER: "postgres"
    DB_PASSWORD: "Elgatopanzon7"
    DB_SSL: "true"
    NODE_ENV: "production"
backend:
  phases:
    build:
      commands:
        - cd backend
        - npm install
        - echo "Configurando variables de entorno..."
        - echo "DB_HOST=$DB_HOST" > .env
        - echo "DB_PORT=$DB_PORT" >> .env
        - echo "DB_NAME=$DB_NAME" >> .env
        - echo "DB_USER=$DB_USER" >> .env
        - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        - echo "DB_SSL=$DB_SSL" >> .env
        - echo "NODE_ENV=production" >> .env
        - npm run setup:prod
        - npm run migrate:all
        - npm run seed:prod
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - backend/node_modules/**/*
