-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. PROFILES Table (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  full_name text,
  role text check (role in ('admin', 'buyer')) default 'buyer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- 2. SUPPLIERS Table
create table public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  ruc text unique,
  contact_name text,
  contact_email text,
  contact_phone text,
  category text, -- 'Technology', 'Office', etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.suppliers enable row level security;

create policy "Suppliers are viewable by authenticated users" on public.suppliers
  for select using (auth.role() = 'authenticated');
  
create policy "Admins can insert suppliers" on public.suppliers
  for insert with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- 3. ORDERS Table
create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null, -- Usage: OC-2025-001
  user_id uuid references public.profiles(id) not null,
  supplier_id bigint references public.suppliers(id),
  status text check (status in ('draft', 'created', 'review', 'approved', 'rejected', 'completed', 'cancelled')) default 'draft',
  total_amount numeric(10,2) default 0.00,
  priority text default 'normal',
  
  -- Request Details
  department text, -- Unidad Negocio
  authorizer_unit text,
  delivery_location text,
  project_details text,
  
  -- Logic Fields
  whatsapp_token text, -- For approval link
  rejection_reason text,
  
  approved_at timestamp with time zone,
  approved_by text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;

create policy "Users can see their own orders" on public.orders
  for select using (auth.uid() = user_id);

create policy "Admins can see all orders" on public.orders
  for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can insert their own orders" on public.orders
  for insert with check (auth.uid() = user_id);

-- 4. ORDER ITEMS Table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  description text not null,
  quantity numeric(10,2) not null,
  unit_price numeric(10,2) not null,
  unit_measure text default 'und',
  subtotal numeric(10,2) generated always as (quantity * unit_price) stored,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.order_items enable row level security;

create policy "Items viewable by order owner" on public.order_items
  for select using (
    exists (select 1 from public.orders where id = order_items.order_id and user_id = auth.uid())
  );

create policy "Items viewable by admin" on public.order_items
  for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can insert items for own orders" on public.order_items
  for insert with check (
    exists (select 1 from public.orders where id = order_items.order_id and user_id = auth.uid())
  );

-- 5. FUNCTION to handle New User -> Profile
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'buyer');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
